# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Docs
    url: /docs/
    weight: 20
  - name: Community
    url: /community/
    weight: 30

sidebar:
  - identifier: overview
    name: Overview
    pageRef: "/docs/overview"
    weight: 1
  - identifier: user
    name: User Guides
    pageRef: "/docs/user"
    weight: 2
  - identifier: community
    name: Community
    pageRef: "/docs/community"
    weight: 3
  - identifier: policies
    name: Policies
    pageRef: "/docs/policies"
    weight: 4
  - identifier: operations
    name: Operations
    pageRef: "/docs/operations"
    weight: 5
  - identifier: transparency
    name: Transparency
    pageRef: "/docs/transparency"
    weight: 6
  - identifier: legal
    name: Legal
    pageRef: "/docs/legal"
    weight: 7
  - identifier: more
    name: Need help?
    params:
      type: separator
    weight: 90
