# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Docs
    url: /docs/
    weight: 20
  - name: Community
    url: community/
    weight: 30

sidebar:
  - identifier: more
    name: Need help?
    params:
      type: separator
    weight: 1
  - identifier: community
    name: "Community"
    pageRef: "/community"
    weight: 2
