# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Docs
    url: /docs/
    weight: 20
  - name: Community
    url: community/
    weight: 30

sidebar:
  - identifier: overview
    name: Overview
    pageRef: "/docs/overview"
    weight: 1
  - identifier: policies
    name: Policies
    pageRef: "/docs/policies"
    weight: 2
  - identifier: operations
    name: Operations
    pageRef: "/docs/operations"
    weight: 3
  - identifier: more
    name: Need help?
    params:
      type: separator
    weight: 90
  - identifier: community
    name: "Community"
    pageRef: "/community"
    weight: 100
