name: Vale

on:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: errata-ai/vale-action@v2
        with:
          config: .vale.ini
          files: .
